// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface CleanItem {
    "id": string;
    "path": string;
    "bytes": number;
    "blocked": string;
    "mtime": number;
}

export interface CleanPlan {
    "token": string;
    "kind": string;
    "items": CleanItem[] | null;
    "bytes": number;
    "expires": string;
}

export interface CleanResult {
    "id": string;
    "success": boolean;
    "message": string;
}

export interface Day {
    "date": string;
    "total": number;
}

export interface Detail {
    "session": Session;
    "messages": Message[] | null;
    "truncated": boolean;
}

export interface Evidence {
    "sessionId": string;
    "project": string;
    "kind": string;
    "path": string;
}

export interface Message {
    "role": string;
    "text": string;
    "time": string;
}

export interface Project {
    "path": string;
    "name": string;
    "sessions": number;
    "bytes": number;
    "usage": Usage;
}

export interface ScanStatus {
    "running": boolean;
    "phase": string;
    "done": number;
    "total": number;
    "errors": string[] | null;
    "finished": string;
}

export interface Session {
    "id": string;
    "path": string;
    "project": string;
    "title": string;
    "model": string;
    "created": string;
    "updated": string;
    "parent": string;
    "size": number;
    "mtime": number;
    "archived": boolean;
    "missing": boolean;
    "warning": string;
    "usage": Usage;
}

export interface SessionPage {
    "items": Session[] | null;
    "total": number;
}

export interface SessionQuery {
    "search": string;
    "project": string;
    "state": string;
    "sort": string;
    "page": number;
}

export interface Snapshot {
    "projects": Project[] | null;
    "usage": Usage;
    "sessions": number;
    "bytes": number;
    "days": Day[] | null;
    "storage": Storage[] | null;
    "home": string;
    "database": string;
    "tempRoots": string[] | null;
    "lastScan": string;
}

export interface Storage {
    "path": string;
    "bytes": number;
    "error": string;
}

export interface TempFile {
    "path": string;
    "name": string;
    "bytes": number;
    "modified": string;
    "mtime": number;
    "isDir": boolean;
    "link": boolean;
    "evidence": Evidence[] | null;
    "error": string;
}

export interface Usage {
    "input": number;
    "cached": number;
    "output": number;
    "reasoning": number;
    "total": number;
}
