// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function ExecuteClean(token: string, confirmation: string): $CancellablePromise<$models.CleanResult[] | null> {
    return $Call.ByID(3225958592, token, confirmation);
}

export function Overview(since: string, until: string): $CancellablePromise<$models.Snapshot> {
    return $Call.ByID(2324921327, since, until);
}

export function PreviewClean(kind: string, ids: string[] | null): $CancellablePromise<$models.CleanPlan> {
    return $Call.ByID(3493913585, kind, ids);
}

export function ResumeCommand(id: string): $CancellablePromise<string> {
    return $Call.ByID(3990437484, id);
}

export function SessionDetail(id: string): $CancellablePromise<$models.Detail> {
    return $Call.ByID(2557750121, id);
}

export function Sessions(q: $models.SessionQuery): $CancellablePromise<$models.SessionPage> {
    return $Call.ByID(204430561, q);
}

export function SetArchived(id: string, archive: boolean): $CancellablePromise<void> {
    return $Call.ByID(2447377114, id, archive);
}

export function StartScan(includeTemps: boolean): $CancellablePromise<void> {
    return $Call.ByID(347407065, includeTemps);
}

export function Status(): $CancellablePromise<$models.ScanStatus> {
    return $Call.ByID(2063583382);
}

export function TempFiles(): $CancellablePromise<$models.TempFile[] | null> {
    return $Call.ByID(2739829693);
}
