// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface State {
    "currentVersion": string;
    "latestVersion": string;
    "phase": string;
    "notes": string;
    "releaseName": string;
    "releaseURL": string;
    "checkedAt": string;
    "written": number;
    "total": number;
    "canInstall": boolean;
    "error": string;
}
