// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Check(): $CancellablePromise<void> {
    return $Call.ByID(3859495213);
}

export function Download(): $CancellablePromise<void> {
    return $Call.ByID(2843489807);
}

export function Restart(): $CancellablePromise<void> {
    return $Call.ByID(480873170);
}

export function Status(): $CancellablePromise<$models.State> {
    return $Call.ByID(1303305197);
}
